# 10: Hva har total forbruk og gj. snitt forbruk vært for ulike ekvipasjer

In [198]:
%load_ext autoreload
%autoreload 2

import pandas as pd
import matplotlib.pyplot as plt
from source.features_dir import vehicle_data_74t

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [199]:
df = vehicle_data_74t.df_truck_vehicle_data()

In [200]:
df.dtypes

VIN                               object
Registreringsnummer              float64
Organisasjonsnummer                int64
Dato                              object
AdBluesnitt (l/mil)               object
Snittforbruk totalt (l/mil)       object
Snittforbruk kjøring (l/mil)     float64
Kjørehastighet                    object
Snitthastighet                    object
CO₂ snitt (kg/h)                  object
CO₂ snitt (kg/km)                 object
CO₂ (tonn)                        object
Distanse (km)                    float64
Distanse med lav vekt (km)       float64
Distanse med medium vekt (km)    float64
Distanse med full vekt (km)      float64
Kjøretid (sekunder)               object
Tomgangstid (sekunder)            object
Tomgangsprosent                  float64
Kraftuttakstid (sekunder)         object
Motortid (sekunder)               object
Liter kjøring                    float64
Liter tomgang                     object
Snittforbruk (l/time)             object
Liter totalt                      object
Min vekt                         float64
Max vekt                         float64
Snittvekt                         object
år                                 int32
ekvipasje                         object
dtype: object

In [201]:
df.isna().sum()

VIN                                  0
Registreringsnummer              12951
Organisasjonsnummer                  0
Dato                                 0
AdBluesnitt (l/mil)               7995
Snittforbruk totalt (l/mil)         33
Snittforbruk kjøring (l/mil)         0
Kjørehastighet                       3
Snitthastighet                       3
CO₂ snitt (kg/h)                    17
CO₂ snitt (kg/km)                   33
CO₂ (tonn)                          33
Distanse (km)                        0
Distanse med lav vekt (km)        7995
Distanse med medium vekt (km)     7995
Distanse med full vekt (km)       7995
Kjøretid (sekunder)                  0
Tomgangstid (sekunder)               0
Tomgangsprosent                      2
Kraftuttakstid (sekunder)            0
Motortid (sekunder)                  0
Liter kjøring                        0
Liter tomgang                        2
Snittforbruk (l/time)                3
Liter totalt                         0
Min vekt                          6982
Max vekt                          6982
Snittvekt                          120
år                                   0
ekvipasje                            0
dtype: int64

In [204]:
df['mil'] = df['Distanse (km)'] / 10

df_agg = df.groupby(['ekvipasje']).agg(
    liter_kjoring=('Liter kjøring', 'sum'),
    mil=('mil', 'sum')
).reset_index()

df_agg['forbruk'] = df_agg['liter_kjoring'] / df_agg['mil']
df_agg

,ekvipasje,liter_kjoring,mil,forbruk
0,3-akslet trekkvogn med 4-akslet tilhenger,670074.93,133568.5,5.016714
1,3-akslet trekkvogn med 5-akslet tilhenger,1126281.97,215585.1,5.224303
2,4-akslet trekkvogn med 4-akslet tilhenger,235562.60,45818.8,5.141178
3,4-akslet trekkvogn med 5-akslet tilhenger,491254.53,87537.2,5.611952

In [210]:
df_agg = df.groupby(['år', 'ekvipasje']).agg(
    liter_kjoring=('Liter kjøring', 'sum'),
    mil=('mil', 'sum')
)

df_agg['forbruk'] = df_agg['liter_kjoring'] / df_agg['mil']
df_agg

                                                liter_kjoring      mil  \
år   ekvipasje
2021 3-akslet trekkvogn med 4-akslet tilhenger      136949.44  28291.4
     3-akslet trekkvogn med 5-akslet tilhenger      164259.93  32659.3
     4-akslet trekkvogn med 4-akslet tilhenger        5657.66   1219.3
     4-akslet trekkvogn med 5-akslet tilhenger       79115.06  13729.3
2022 3-akslet trekkvogn med 4-akslet tilhenger      186988.29  37429.4
     3-akslet trekkvogn med 5-akslet tilhenger      292490.64  56879.3
     4-akslet trekkvogn med 4-akslet tilhenger       58789.83  12260.1
     4-akslet trekkvogn med 5-akslet tilhenger       76515.14  13606.0
2023 3-akslet trekkvogn med 4-akslet tilhenger      182457.00  35630.6
     3-akslet trekkvogn med 5-akslet tilhenger      383403.68  72419.5
     4-akslet trekkvogn med 4-akslet tilhenger       81440.52  15306.3
     4-akslet trekkvogn med 5-akslet tilhenger      166325.37  29629.3
2024 3-akslet trekkvogn med 4-akslet tilhenger      163680.20  32217.1
     3-akslet trekkvogn med 5-akslet tilhenger      286127.72  53627.0
     4-akslet trekkvogn med 4-akslet tilhenger       89674.59  17033.1
     4-akslet trekkvogn med 5-akslet tilhenger      169298.96  30572.6

                                                 forbruk
år   ekvipasje
2021 3-akslet trekkvogn med 4-akslet tilhenger  4.840674
     3-akslet trekkvogn med 5-akslet tilhenger  5.029499
     4-akslet trekkvogn med 4-akslet tilhenger  4.640089
     4-akslet trekkvogn med 5-akslet tilhenger  5.762498
2022 3-akslet trekkvogn med 4-akslet tilhenger  4.995760
     3-akslet trekkvogn med 5-akslet tilhenger  5.142304
     4-akslet trekkvogn med 4-akslet tilhenger  4.795216
     4-akslet trekkvogn med 5-akslet tilhenger  5.623632
2023 3-akslet trekkvogn med 4-akslet tilhenger  5.120795
     3-akslet trekkvogn med 5-akslet tilhenger  5.294205
     4-akslet trekkvogn med 4-akslet tilhenger  5.320719
     4-akslet trekkvogn med 5-akslet tilhenger  5.613544
2024 3-akslet trekkvogn med 4-akslet tilhenger  5.080538
     3-akslet trekkvogn med 5-akslet tilhenger  5.335516
     4-akslet trekkvogn med 4-akslet tilhenger  5.264725
     4-akslet trekkvogn med 5-akslet tilhenger  5.537604